//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepliesPublicConsultation
    {
        public int Id { get; set; }
        public Nullable<int> PublicConsultationId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ProfessorId { get; set; }
        public string DateTime { get; set; }
        public string Motive { get; set; }
    
        public virtual Professor Professor { get; set; }
        public virtual PublicConsultation PublicConsultation { get; set; }
        public virtual Student Student { get; set; }
    }
}
