USE [API_IF4101APILPAC]
CREATE TABLE News(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
AuthorId INT NOT NULL,
AuthorName VARCHAR(50) NOT NULL,
DateTime VARCHAR(50) NOT NULL,
Text VARCHAR(3000) NOT NULL,
Title VARCHAR(200))

------------------------------

CREATE TABLE Comment(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
AuthorId INT NOT NULL,
AuthorName VARCHAR(50) NOT NULL,
DateTime VARCHAR(50) NOT NULL,
Text VARCHAR(500) NOT NULL,
NewsId INT NOT NULL,
FOREIGN KEY (NewsId) REFERENCES News (Id)
)