//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialNetworksProfessor
    {
        public int Id { get; set; }
        public Nullable<int> ProfessorId { get; set; }
        public string Url { get; set; }
        public Nullable<int> SocialNetworksNameId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Professor Professor { get; set; }
        public virtual SocialNetworksCatalog SocialNetworksCatalog { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
